### ISSUE TITLE
Syntax Error: Use of const in strict mode.

### ISSUE THREAD

**Issue by mamund** [kevinswiber/sirenlint#2]
harmony issue?

i'm running node v0.10.25 on this machine.

**Comment by kevinswiber** [comment]
Hey @mamund, thanks for reporting this! It should be fixed in the latest version.  Try running `npm update sirenlint -g`.

**Comment by kevinswiber** [comment]
Or maybe... `npm install sirenlint@0.3.0 -g`.  I forget if the global update works or not.

**Comment by mamund** [comment]
works like a champ!

_excellent_

**Comment by mamund** [comment]
update worked fine for me.

thanks.
​
